### ISSUE TITLE
Error in v 0.1.2

### ISSUE THREAD

**Issue by gruntikFor** [gurock/testrail-junit-extensions#8]
I get an error in version 0.1.2, in version 0.1.1 everything works.

`Dec 18, 2023 9:32:14 AM org.junit.platform.launcher.core.CompositeTestExecutionListener lambda$notifyEach$19
WARNING: TestExecutionListener [com.testrail.junit.customjunitxml.EnhancedLegacyXmlReportGeneratingListener] threw exception for method: executionFinished(TestIdentifier [uniqueId = [engine:junit-vintage], parentId = null, displayName = 'JUnit Vintage', legacyReportingName = 'JUnit Vintage', source = null, tags = [], type = CONTAINER], TestExecutionResult [status = SUCCESSFUL, throwable = null])
java.lang.IllegalArgumentException: Unrecognized property 'escapeCharacters'
	at com.ctc.wstx.api.CommonConfig.reportUnknownProperty(CommonConfig.java:167)
	at com.ctc.wstx.api.CommonConfig.setProperty(CommonConfig.java:158)
	at com.ctc.wstx.api.WriterConfig.setProperty(WriterConfig.java:23)
	at com.ctc.wstx.stax.WstxOutputFactory.setProperty(WstxOutputFactory.java:175)
	at com.testrail.junit.customjunitxml.XmlReportWriter.writeXmlReport(XmlReportWriter.java:129)
	at com.testrail.junit.customjunitxml.XmlReportWriter.writeXmlReport(XmlReportWriter.java:111)
	at com.testrail.junit.customjunitxml.EnhancedLegacyXmlReportGeneratingListener.writeXmlReportSafely(EnhancedLegacyXmlReportGeneratingListener.java:183)
	at com.testrail.junit.customjunitxml.EnhancedLegacyXmlReportGeneratingListener.writeXmlReportInCaseOfRoot(EnhancedLegacyXmlReportGeneratingListener.java:163)
	at com.testrail.junit.customjunitxml.EnhancedLegacyXmlReportGeneratingListener.executionFinished(EnhancedLegacyXmlReportGeneratingListener.java:157)
	at org.junit.platform.launcher.core.CompositeTestExecutionListener.lambda$executionFinished$10(CompositeTestExecutionListener.java:69)
	at org.junit.platform.launcher.core.CompositeTestExecutionListener.lambda$notifyEach$19(CompositeTestExecutionListener.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.launcher.core.CompositeTestExecutionListener.notifyEach(CompositeTestExecutionListener.java:93)
	at org.junit.platform.launcher.core.CompositeTestExecutionListener.executionFinished(CompositeTestExecutionListener.java:69)
	at org.junit.platform.launcher.core.ExecutionListenerAdapter.executionFinished(ExecutionListenerAdapter.java:56)
	at org.junit.platform.launcher.core.DelegatingEngineExecutionListener.executionFinished(DelegatingEngineExecutionListener.java:46)
	at org.junit.platform.launcher.core.OutcomeDelayingEngineExecutionListener.reportEngineOutcome(OutcomeDelayingEngineExecutionListener.java:69)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)`

**Comment by bitcoder** [comment]
Hmm.. maybe it was introduced by the changes on commit https://github.com/gurock/testrail-junit-extensions/commit/055138fa8c30b34b68c8b9a69d81239857da2116  for #7  
Can you provide a sample project with a basic example that replicates this as I can't?

**Comment by Blezur** [comment]
@bitcoder I have same problem with escapeCharacters. I downloaded the sample from your page and just changed version to the 0.1.2.

**Comment by bitcoder** [comment]
Can any of you please provide a sample so that we can replicate this problem?

**Comment by bitcoder** [comment]
Can you please try it with v0.2.0 released today and give feedback if it works?
Also, if it doesnt work can you please provide a sample so we can replicate it?
Else, I'll close this issue in the next days.

**Comment by gruntikFor** [comment]
In last version 0.2.1 everything fine. 
Thanks for your work! 
Sorry for the long answer.
